# Generated by Django 2.1.2 on 2018-11-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('r_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('r_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_score', models.CharField(max_length=3)),
                ('c_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_sex', models.CharField(max_length=10)),
                ('s_tel', models.CharField(max_length=11)),
                ('s_cid', models.ManyToManyField(to='app1.Course')),
                ('s_rname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=20)),
                ('t_sex', models.CharField(max_length=10)),
                ('t_pos', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='c_tid',
            field=models.ManyToManyField(to='app1.Teacher'),
        ),
    ]
