# Generated by Django 2.1.2 on 2018-11-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181123_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=3, null=True)),
                ('c_name', models.CharField(max_length=30)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Course')),
                ('s_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Student')),
            ],
        ),
    ]
